'use strict'; // code generated by pbf v3.3.0

// GetInvestmentsRorMetricsResponse ========================================

var GetInvestmentsRorMetricsResponse = exports.GetInvestmentsRorMetricsResponse = {};

GetInvestmentsRorMetricsResponse.read = function (pbf, end) {
    return pbf.readFields(GetInvestmentsRorMetricsResponse._readField, {investmentsRorMetrics: []}, end);
};
GetInvestmentsRorMetricsResponse._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.investmentsRorMetrics.push(InvestmentsRorMetric.read(pbf, pbf.readVarint() + pbf.pos));
};
GetInvestmentsRorMetricsResponse.write = function (obj, pbf) {
    if (obj.investmentsRorMetrics) for (var i = 0; i < obj.investmentsRorMetrics.length; i++) pbf.writeMessage(1, InvestmentsRorMetric.write, obj.investmentsRorMetrics[i]);
};

// InvestmentsRorMetric ========================================

var InvestmentsRorMetric = exports.InvestmentsRorMetric = {};

InvestmentsRorMetric.read = function (pbf, end) {
    return pbf.readFields(InvestmentsRorMetric._readField, {metric: "", pf: undefined, nps: undefined, lic: undefined, share: undefined, mf: undefined, total: undefined}, end);
};
InvestmentsRorMetric._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.metric = pbf.readString();
    else if (tag === 2) obj.pf = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 3) obj.nps = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 4) obj.lic = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 5) obj.share = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 6) obj.mf = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 7) obj.total = InvestmentsReturn.read(pbf, pbf.readVarint() + pbf.pos);
};
InvestmentsRorMetric.write = function (obj, pbf) {
    if (obj.metric) pbf.writeStringField(1, obj.metric);
    if (obj.pf) pbf.writeMessage(2, InvestmentsReturn.write, obj.pf);
    if (obj.nps) pbf.writeMessage(3, InvestmentsReturn.write, obj.nps);
    if (obj.lic) pbf.writeMessage(4, InvestmentsReturn.write, obj.lic);
    if (obj.share) pbf.writeMessage(5, InvestmentsReturn.write, obj.share);
    if (obj.mf) pbf.writeMessage(6, InvestmentsReturn.write, obj.mf);
    if (obj.total) pbf.writeMessage(7, InvestmentsReturn.write, obj.total);
};

// InvestmentsReturn ========================================

var InvestmentsReturn = exports.InvestmentsReturn = {};

InvestmentsReturn.read = function (pbf, end) {
    return pbf.readFields(InvestmentsReturn._readField, {beg: 0, end: 0, inv: 0, ror: 0}, end);
};
InvestmentsReturn._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.beg = pbf.readVarint(true);
    else if (tag === 2) obj.end = pbf.readVarint(true);
    else if (tag === 3) obj.inv = pbf.readVarint(true);
    else if (tag === 4) obj.ror = pbf.readDouble();
};
InvestmentsReturn.write = function (obj, pbf) {
    if (obj.beg) pbf.writeVarintField(1, obj.beg);
    if (obj.end) pbf.writeVarintField(2, obj.end);
    if (obj.inv) pbf.writeVarintField(3, obj.inv);
    if (obj.ror) pbf.writeDoubleField(4, obj.ror);
};
