'use strict'; // code generated by pbf v3.3.0

// GetInvestmentsResponse ========================================

var GetInvestmentsResponse = exports.GetInvestmentsResponse = {};

GetInvestmentsResponse.read = function (pbf, end) {
    return pbf.readFields(GetInvestmentsResponse._readField, {investmentAmount: 0, asOnValue: 0, investmentsByType: {}, investmentsValueByType: {}, monthInvestments: []}, end);
};
GetInvestmentsResponse._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.investmentAmount = pbf.readVarint(true);
    else if (tag === 2) obj.asOnValue = pbf.readVarint(true);
    else if (tag === 3)  { var entry = GetInvestmentsResponse._FieldEntry3.read(pbf, pbf.readVarint() + pbf.pos); obj.investmentsByType[entry.key] = entry.value; }
    else if (tag === 4)  { entry = GetInvestmentsResponse._FieldEntry4.read(pbf, pbf.readVarint() + pbf.pos); obj.investmentsValueByType[entry.key] = entry.value; }
    else if (tag === 5) obj.monthInvestments.push(MonthInvestment.read(pbf, pbf.readVarint() + pbf.pos));
};
GetInvestmentsResponse.write = function (obj, pbf) {
    if (obj.investmentAmount) pbf.writeVarintField(1, obj.investmentAmount);
    if (obj.asOnValue) pbf.writeVarintField(2, obj.asOnValue);
    if (obj.investmentsByType) for (var i in obj.investmentsByType) if (Object.prototype.hasOwnProperty.call(obj.investmentsByType, i)) pbf.writeMessage(3, GetInvestmentsResponse._FieldEntry3.write, { key: i, value: obj.investmentsByType[i] });
    if (obj.investmentsValueByType) for (i in obj.investmentsValueByType) if (Object.prototype.hasOwnProperty.call(obj.investmentsValueByType, i)) pbf.writeMessage(4, GetInvestmentsResponse._FieldEntry4.write, { key: i, value: obj.investmentsValueByType[i] });
    if (obj.monthInvestments) for (i = 0; i < obj.monthInvestments.length; i++) pbf.writeMessage(5, MonthInvestment.write, obj.monthInvestments[i]);
};

// GetInvestmentsResponse._FieldEntry3 ========================================

GetInvestmentsResponse._FieldEntry3 = {};

GetInvestmentsResponse._FieldEntry3.read = function (pbf, end) {
    return pbf.readFields(GetInvestmentsResponse._FieldEntry3._readField, {key: "", value: 0}, end);
};
GetInvestmentsResponse._FieldEntry3._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.key = pbf.readString();
    else if (tag === 2) obj.value = pbf.readVarint(true);
};
GetInvestmentsResponse._FieldEntry3.write = function (obj, pbf) {
    if (obj.key) pbf.writeStringField(1, obj.key);
    if (obj.value) pbf.writeVarintField(2, obj.value);
};

// GetInvestmentsResponse._FieldEntry4 ========================================

GetInvestmentsResponse._FieldEntry4 = {};

GetInvestmentsResponse._FieldEntry4.read = function (pbf, end) {
    return pbf.readFields(GetInvestmentsResponse._FieldEntry4._readField, {key: "", value: 0}, end);
};
GetInvestmentsResponse._FieldEntry4._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.key = pbf.readString();
    else if (tag === 2) obj.value = pbf.readVarint(true);
};
GetInvestmentsResponse._FieldEntry4.write = function (obj, pbf) {
    if (obj.key) pbf.writeStringField(1, obj.key);
    if (obj.value) pbf.writeVarintField(2, obj.value);
};

// MonthInvestment ========================================

var MonthInvestment = exports.MonthInvestment = {};

MonthInvestment.read = function (pbf, end) {
    return pbf.readFields(MonthInvestment._readField, {yearMonth: "", investmentAmount: 0, asOnInvestment: 0, asOnValue: 0, investments: []}, end);
};
MonthInvestment._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.yearMonth = pbf.readString();
    else if (tag === 2) obj.investmentAmount = pbf.readVarint(true);
    else if (tag === 3) obj.asOnInvestment = pbf.readVarint(true);
    else if (tag === 4) obj.asOnValue = pbf.readVarint(true);
    else if (tag === 5) obj.investments.push(Investment.read(pbf, pbf.readVarint() + pbf.pos));
};
MonthInvestment.write = function (obj, pbf) {
    if (obj.yearMonth) pbf.writeStringField(1, obj.yearMonth);
    if (obj.investmentAmount) pbf.writeVarintField(2, obj.investmentAmount);
    if (obj.asOnInvestment) pbf.writeVarintField(3, obj.asOnInvestment);
    if (obj.asOnValue) pbf.writeVarintField(4, obj.asOnValue);
    if (obj.investments) for (var i = 0; i < obj.investments.length; i++) pbf.writeMessage(5, Investment.write, obj.investments[i]);
};

// Investment ========================================

var Investment = exports.Investment = {};

Investment.read = function (pbf, end) {
    return pbf.readFields(Investment._readField, {head: "", investmentAmount: 0, asOnInvestment: 0, asOnValue: 0}, end);
};
Investment._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.head = pbf.readString();
    else if (tag === 2) obj.investmentAmount = pbf.readVarint(true);
    else if (tag === 3) obj.asOnInvestment = pbf.readVarint(true);
    else if (tag === 4) obj.asOnValue = pbf.readVarint(true);
};
Investment.write = function (obj, pbf) {
    if (obj.head) pbf.writeStringField(1, obj.head);
    if (obj.investmentAmount) pbf.writeVarintField(2, obj.investmentAmount);
    if (obj.asOnInvestment) pbf.writeVarintField(3, obj.asOnInvestment);
    if (obj.asOnValue) pbf.writeVarintField(4, obj.asOnValue);
};
