'use strict'; // code generated by pbf v3.3.0

// GetRawInvestmentsResponse ========================================

var GetRawInvestmentsResponse = exports.GetRawInvestmentsResponse = {};

GetRawInvestmentsResponse.read = function (pbf, end) {
    return pbf.readFields(GetRawInvestmentsResponse._readField, {investments: []}, end);
};
GetRawInvestmentsResponse._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.investments.push(Investment.read(pbf, pbf.readVarint() + pbf.pos));
};
GetRawInvestmentsResponse.write = function (obj, pbf) {
    if (obj.investments) for (var i = 0; i < obj.investments.length; i++) pbf.writeMessage(1, Investment.write, obj.investments[i]);
};

// Investment ========================================

var Investment = exports.Investment = {};

Investment.read = function (pbf, end) {
    return pbf.readFields(Investment._readField, {id: 0, yearx: 0, monthx: 0, head: "", contribution: 0, valueAsOnMonth: 0, contributionAsOnMonth: 0}, end);
};
Investment._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint(true);
    else if (tag === 2) obj.yearx = pbf.readVarint(true);
    else if (tag === 3) obj.monthx = pbf.readVarint(true);
    else if (tag === 4) obj.head = pbf.readString();
    else if (tag === 5) obj.contribution = pbf.readVarint(true);
    else if (tag === 6) obj.valueAsOnMonth = pbf.readVarint(true);
    else if (tag === 7) obj.contributionAsOnMonth = pbf.readVarint(true);
};
Investment.write = function (obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.yearx) pbf.writeVarintField(2, obj.yearx);
    if (obj.monthx) pbf.writeVarintField(3, obj.monthx);
    if (obj.head) pbf.writeStringField(4, obj.head);
    if (obj.contribution) pbf.writeVarintField(5, obj.contribution);
    if (obj.valueAsOnMonth) pbf.writeVarintField(6, obj.valueAsOnMonth);
    if (obj.contributionAsOnMonth) pbf.writeVarintField(7, obj.contributionAsOnMonth);
};
